# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfd1b667afd21ae3b02658f51b569714f04a20cf69d6b25c8ccec0e5fbc9ea4fc6921e0c79dc0932c8c150f5a0acadcfac91467456110241f9b20556b5c1b536

test:
  secret_key_base: 0ac2134134eb5143bd37d20a72979065bd282cec05d42efb2b74e61e72ee5068bc1b6701171ca449ea913da8125722e5aa8d14d0d8280b4dbb7bb419b6b1fc76

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
